[DocsUI tests] Add functional tests for sync state
Add tests for:
- the "You're offline" banner
- the inine sync state icons
- the context/action menus (to ensure certain items get disabled offline)

Create a TestCloudProvider that sets the FLAG_LIMITED_FUNCTIONALITY_WHEN_OFFLINE
root flag and the COLUMN_CONTENT_SYNC_STATE_FLAGS for documents.

Add helper methods in DocumentsProviderHelper to allow tests to set the
sync state document column.

Modify NetworkMonitor, BaseActivity and ActivityTestJunit4 so that
functional tests can fake the
- "is online" state of the NetworkMonitorImpl
- inline sync tick icon visibility duration

Also fix the DirectoryListBot.findDocument function to handle when the
document is behind the breadcrumb. This can occur when trying to find
the virtual (last) document in the tests.

Note that the Espresso method openRoot was avoided in the tests as it
kept causing this error for no apparent reason:
Caused by: androidx.test.espresso.PerformException: Error performing 'click (after 3 attempts)' on view 'unknown'.

Note that com.android.documentsui.util.FlagUtils can't be used for some
reason in the TestCloudProvider as usage always leads to a
NoClassDefFoundError. So we avoid using it and simply call the static
API constants without a check. This is safe because they will be
available during compilation and inserted inline.

Bug: 473413504
Bug: 478968493
Flag: com.android.documentsui.flags.cloud_features
Flag: com.android.documentsui.flags.use_material3
Flag: android.provider.enable_sync_state
Test: com.android.documentsui.SyncStateUiTest
Change-Id: Ia29bd951f22af77983c96cc94f64a99327b4c5fa