Revert "[DocsUI M3] Rename PickFragment to PickDirectoryFragment"
This reverts commit 444098adb07c034789f32ced05225d756ce2d454.

Reason for revert: This breaks all DocumentsUI tests with the following
error:

java.lang.NoSuchFieldError: No static field fragment_pick_directory of
type I in class Lcom/android/documentsui/R$layout; or its superclasses
(declaration of 'com.android.documentsui.R$layout' appears in
/data/app/~~rZhhZjMEqEqxGhzZelo2Jw==/com.google.android.documentsui-xRFM1j3AfYiCxafvynYzug==/base.apk)

Bug: 409931248
Bug: 409985958
Fix: 411421883
Fix: 411376312
Change-Id: I7d1085722111c96afc72cd1642a3f5112e249823