[DocsUI] Use the new sync state DocumentsContract constants
Previously local constants were defined to avoid using the new sync
state DocumentsContract constants.

This CL replaces the local constants with the real DocumentsContract.
ones. Their usage needs to be guarded by the android.provider flag
FLAG_ENABLE_SYNC_STATE.

There is the new enableSyncState() method which returns the value
of the @FlaggedApi(Flags.FLAG_ENABLE_SYNC_STATE) which guards these
static constants. This should default to false if the device DocsUI
is running on is using an older SDK version that doesn't include
this API flag (go/android-api-flagging-faq#api-finalization). However,
this doesn't work on Android U (API level 34) and a
NoSuchMethodError will be thrown if enableSyncState() is called.
Therefore guarding is required.

This sync state API is targeting API level 37, however the version
bump hasn't occurred yet so guard to ensure that the API level is
at least 36 (Android B).

The tests also need to be guarded with @SdkSuppress(BAKLAVA) to
avoid a NoSuchMethodException due to a
@RequiresFlagsEnabled(android.provider.Flags.FLAG_ENABLE_SYNC_STATE)
on Android U.

[1] https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#:~:text=If%20such%20a,never%20be%20observed

Flag: com.android.documentsui.flags.use_material3
Flag: com.android.documentsui.flags.cloud_features
Test: atest com.android.documentsui.dirlist.DirectoryAddonsAdapterTest
Test: atest com.android.documentsui.dirlist.DirectoryFragmentTest
Test: atest com.android.documentsui.dirlist.ModelBackedDocumentsAdapterTest
Test: atest com.android.documentsui.ActivityConfigTest
Test: atest com.android.documentsui.base.DocumentInfoTest
Test: atest com.android.documentsui.base.NetworkMonitorTest
Test: atest com.android.documentsui.dirlist.DocumentHolderTest
Test: atest com.android.documentsui.dirlist.DragStartListenerTest
Test: atest com.android.documentsui.dirlist.MessageTest
Test: atest com.android.documentsui.dirlist.SelectionMetadataTest
Test: atest com.android.documentsui.files.ActionHandlerTest
Test: atest com.android.documentsui.files.MenuManagerTest
Test: atest com.android.documentsui.DragAndDropManagerTests
Test: atest com.android.documentsui.ModelTest
Test: atest com.android.documentsui.picker.ConfigTest
Bug: 458129770

Change-Id: I8890ef6b5bf6aabe86035ba51c9b885422aa8b51